function ptrDsSecuence (hMainWin)
    ptrData = guidata (hMainWin);

    pnPos = [0, ptrData.params.statusBarHeight, ...
             ptrData.params.mainWinSize(1), ...
             ptrData.params.mainWinSize(2) - ptrData.params.statusBarHeight];
                         
    buttonsBarHeight = 50;
    
    % Deletes the panel if already exists
    if isfield(ptrData.handles,'mainPanel') && ...
            isfield(ptrData.handles.mainPanel,'hPanel') && ...
            ishandle(ptrData.handles.mainPanel.hPanel)
        delete(ptrData.handles.mainPanel.hPanel);
    end
    
    % Creates main panel
    h.hPanel = uipanel('Parent', hMainWin, ...
            'Units','pixels', ...
            'Position', pnPos, ...
            'BorderType','none');    
    
    % Create image panel
    h.imgPanel = uipanel('Parent', h.hPanel, ...
            'Units','pixels', ...
            'Position', [0 buttonsBarHeight ...
                        pnPos(3) pnPos(4) - buttonsBarHeight], ...
            'BackgroundColor', ptrData.params.colormap(1,:), ...
            'BorderType','none');

    % Create  buttons panel
    h.btnPanel = uipanel('Parent', h.hPanel, ...
            'Units','pixels', ...
            'Position', [0 0 pnPos(3) buttonsBarHeight], ...
            'BorderType','none');
    bgColor = get(h.btnPanel, 'BackgroundColor');
    
    % Create axes
    h.axes = axes('Parent', h.imgPanel, ...
            'Units', 'normalized', ...
            'Position', [0 0 1 1], ...
            'XTick',[], 'YTick', [], ...
            'Box', 'on');


    % Create buttons
    h.buttonsBar.btnLeft = uicontrol('Parent', h.btnPanel, ...
        'Units','Pixels', ...
        'Position', [10 10 30 30], ...
        'Callback', {'ptrCbSecuence', 'changeImage', -1}, ...
        'TooltipString', ptrLgGetString('secuUI_ImLeftTip'), ...
        'CData', ptrLoadIcon(ptrData.params,'go_left',bgColor));
        
    h.buttonsBar.btnRight = uicontrol('Parent', h.btnPanel, ...
        'Units','Pixels', ...
        'Position', [50 10 30 30], ...
        'Callback', {'ptrCbSecuence', 'changeImage', 1}, ...
        'TooltipString', ptrLgGetString('secuUI_ImRightTip'), ...
        'CData', ptrLoadIcon(ptrData.params,'go_right',bgColor));
        
    % Image number
    h.buttonsBar.txtImgTitle = uicontrol('Parent', h.btnPanel, ...
            'String', [ptrLgGetString('secuUI_ImageTxt') ':'], ...
            'Style','text', ...
            'Units','pixels', ...
            'Position',[130 35 60 12], ...
            'FontUnits','pixels', ...
            'FontName', 'Helvetica', ...
            'FontSize', 10, ...
            'FontWeight', 'normal', ...
            'HorizontalAlignment','left');
        
    h.buttonsBar.txtImg = uicontrol('Parent', h.btnPanel, ...
            'String', '', ...
            'Style','text', ...
            'Units','pixels', ...
            'Position',[160 12 30 15], ...
            'FontUnits','pixels', ...
            'FontName', 'Helvetica', ...
            'FontSize', 13, ...
            'FontWeight', 'bold', ...
            'HorizontalAlignment','left');
        
    % Selection check box
    h.buttonsBar.selCheck = uicontrol( ...
            'Parent', h.btnPanel, ...
            'Style', 'checkbox',...
            'Units', 'Pixels', ...
            'Position', [130 10 20 20], ...
            'Value', ptrData.images(ptrData.current.img).selected, ...
            'Callback', {'ptrCbMainWindow','selectImg'}, ...
            'String', '');

    % Classify button
    h.buttonsBar.btnClassify = uicontrol( ...
            'Parent', h.btnPanel, ...
            'Style', 'pushbutton',...
            'Units', 'Pixels', ...
            'Position', [90 10 30 30], ...
            'Callback', {'ptrCbMainWindow','imgClassify'}, ...
            'TooltipString', ptrLgGetString('secuUI_ClassifyTip'), ...
            'CData', ptrLoadIcon(ptrData.params,'question',bgColor), ...
            'String', '');
        
        
    % Popupmenu for selecting the view
    h.buttonsBar.txtSliceView = uicontrol ('Parent', h.btnPanel, ...
            'String', [ptrLgGetString('secuUI_SliceView') ':'], ...
            'Style','text', ...
            'Units','pixels', ...
            'Position',[200 35 100 12], ...
            'FontUnits','pixels', ...
            'FontName', 'Helvetica', ...
            'FontSize', 10, ...
            'FontWeight', 'normal', ...
            'HorizontalAlignment','left');

    views = {ptrLgGetString('secuUI_ViewAxial'); ...
             ptrLgGetString('secuUI_ViewCoronal'); ...
             ptrLgGetString('secuUI_ViewSagital')};
    h.buttonsBar.cbSliceView = uicontrol ('Parent', h.btnPanel, ...
            'String', views, ...
            'Style','popupmenu', ...
            'Units','pixels', ...
            'Position',[200 15 100 15], ...
            'FontUnits','pixels', ...
            'FontName', 'Helvetica', ...
            'FontSize', 10, ...
            'FontWeight', 'normal', ...
            'Value', ptrData.current.view,...
            'Callback', {'ptrCbSecuence', 'changeView'}, ...
            'HorizontalAlignment','left');
        
    % Slider for selecting the slice
    h.buttonsBar.txtSliceTxt = uicontrol ('Parent', h.btnPanel, ...
            'String', [ptrLgGetString('secuUI_SliceTxt') ':'], ...
            'Style','text', ...
            'Units','pixels', ...
            'Position',[pnPos(3)-190 35 70 12], ...
            'Tag', 'ButtonPanel.SliceControl', ...
            'FontUnits','pixels', ...
            'FontName', 'Helvetica', ...
            'FontSize', 10, ...
            'FontWeight', 'normal', ...
            'HorizontalAlignment','left');
        
    h.buttonsBar.txtSliceIdx = uicontrol ('Parent', h.btnPanel, ...
            'String', '/ ', ...
            'Style','text', ...
            'Units','pixels', ...
            'Position',[pnPos(3)-120 35 30 12], ...
            'Tag', 'ButtonPanel.SliceControl', ...
            'FontUnits','pixels', ...
            'FontName', 'Helvetica', ...
            'FontSize', 10, ...
            'FontWeight', 'normal', ...
            'HorizontalAlignment','right');
        
    h.buttonsBar.sliderSlice = uicontrol(...
            'Parent', h.btnPanel,...
            'Style', 'slider', ...
            'Units','pixels', ...
            'Position', [pnPos(3)-190 15, 100, 15], ...
            'Tag', 'ButtonPanel.SliceControl', ...
            'Callback', {'ptrCbSecuence','changeSlice'}, ...
            'Enable', 'on', ...
            'Min', 0, ...
            'Max', 1, ...
            'SliderStep', [0.1 0.1], ...
            'Value', ptrData.current.slice); 
        
    % Play/stop button
    icons = {ptrLoadIcon(ptrData.params,'stop',bgColor); ...
             ptrLoadIcon(ptrData.params,'play',bgColor)};
    h.buttonsBar.btnLeft = uicontrol('Parent', h.btnPanel, ...
        'Style','togglebutton', ...
        'Units','Pixels', ...
        'Position', [pnPos(3)-80 10 30 30], ...
        'Callback', {'ptrCbSecuence', 'playSlices'}, ...
        'TooltipString', ptrLgGetString('secuUI_PlayTip'), ...
        'Tag', 'ButtonPanel.SliceControl', ...
        'CData', icons{2}, ...
        'UserData', icons);
    
    % All/one slice button
    icons = {ptrLoadIcon(ptrData.params,'sliceOne',bgColor); ...
             ptrLoadIcon(ptrData.params,'sliceAll',bgColor)};
    h.buttonsBar.btnLeft = uicontrol('Parent', h.btnPanel, ...
        'Style','togglebutton', ...
        'Units','Pixels', ...
        'Position', [pnPos(3)-40 10 30 30], ...
        'Callback', {'ptrCbSecuence', 'changeSliceMode'}, ...
        'TooltipString', ptrLgGetString('secuUI_SliceModeTip'), ...
        'CData', icons{2}, ...
        'UserData', icons);
    
    ptrData.handles.mainPanel = h;
    guidata (hMainWin, ptrData);

    % Enable image tools (tool bar)
    ptrPlotTools (ptrData.handles.toolbar.toolbar, [], 'enable', 'on');
    
    % Disable scroll
    set (ptrData.handles.win, 'WindowScrollWheelFcn', '');
    
    ptrCbSecuence(hMainWin, [], 'refreshImage');
end




