
function ptrDsMainWindow (hMainWin)    
    ptrData = guidata (hMainWin);

    % Estimate position centered in the screen
    set (0, 'Units', 'pixels');
    screenSize = get (0, 'ScreenSize');
    mainWinPos = [round((screenSize(3) - ptrData.params.mainWinSize(1))/2) ...
                  round((screenSize(4) - ptrData.params.mainWinSize(2))/2)]; 
    
    % Customize figure properties          
    set(ptrData.handles.win, 'Name', 'Petra', ...
            'NumberTitle', 'off', ...
            'Menubar', 'none', ...
            'DockControls', 'off', ...
            'ResizeFcn',{'ptrCbMainWindow','resizeWindow'}, ...
            'Position', [mainWinPos ptrData.params.mainWinSize]);

    % Images menu
    menu.images.menu = uimenu(ptrData.handles.win,'Label', ...
        ptrLgGetString('menu_Images')); 
    menu.images.item(1) = uimenu(menu.images.menu, ...
            'Label', ptrLgGetString('menu_ImagesOpen'), ...
            'Accelerator','o', ...
            'Callback', {'ptrCbMainWindow','imgOpen'});
    menu.images.item(2) = uimenu(menu.images.menu, ...
            'Label', ptrLgGetString('menu_ImagesSelect'));
    menu.images.item(3) = uimenu(menu.images.item(2), ...
            'Label', ptrLgGetString('menu_ImagesSelectAll'), ...
            'Accelerator','a', ...
            'Callback', {'ptrCbMainWindow','changeSelection','all'});
    menu.images.item(4) = uimenu(menu.images.item(2), ...
            'Label', ptrLgGetString('menu_ImagesSelectNone'), ...
            'Callback', {'ptrCbMainWindow','changeSelection','none'});
    menu.images.item(5) = uimenu(menu.images.item(2), ...
            'Label', ptrLgGetString('menu_ImagesSelectInvert'), ...
            'Callback', {'ptrCbMainWindow','changeSelection','invert'});
    menu.images.item(6) = uimenu(menu.images.menu, ...
            'Label', ptrLgGetString('menu_ImagesSelection'));
    menu.images.itemIm(1) = uimenu(menu.images.item(6), ...
            'Label', ptrLgGetString('menu_ImagesNormSpa'), ...
            'Callback', {'ptrCbMainWindow','imgNormSpa'});
    menu.images.itemIm(2) = uimenu(menu.images.item(6), ...
            'Label', ptrLgGetString('menu_ImagesNormIntMax'), ...
            'Callback', {'ptrCbMainWindow','imgNormInt','Max'});
    menu.images.itemIm(3) = uimenu(menu.images.item(6), ...
            'Label', ptrLgGetString('menu_ImagesNormIntMean'), ...
            'Callback', {'ptrCbMainWindow','imgNormInt','Mean'});
    menu.images.itemIm(4) = uimenu(menu.images.item(6), ...
            'Label', ptrLgGetString('menu_ImagesMarkAsCtl'), ...
            'Separator', 'on', ...
            'Callback', {'ptrCbMainWindow','imgMarkAs','CTL'});
    menu.images.itemIm(5) = uimenu(menu.images.item(6), ...
            'Label', ptrLgGetString('menu_ImagesMarkAsPat'), ...
            'Callback', {'ptrCbMainWindow','imgMarkAs','PAT'});
    menu.images.itemIm(6) = uimenu(menu.images.item(6), ...
            'Label', ptrLgGetString('menu_ImagesSave'), ...
            'Separator', 'on', ...
            'Callback', {'ptrCbMainWindow','imgSave'});
    menu.images.itemIm(7) = uimenu(menu.images.item(6), ...
            'Label', ptrLgGetString('menu_ImagesClose'), ...
            'Callback', {'ptrCbMainWindow','imgClose'});

    % Training menu
    menu.trn.menu = uimenu(ptrData.handles.win,'Label', ...
            ptrLgGetString('menu_Trn'));
    menu.trn.item(1) = uimenu(menu.trn.menu, ...
            'Label', ptrLgGetString('menu_TrnCreate'), ...
            'Callback', {'ptrCbMainWindow','trnCreate'});
    menu.trn.item(2) = uimenu(menu.trn.menu, ...
            'Label', ptrLgGetString('menu_TrnLoad'), ...
            'Accelerator','t', ...
            'Callback', {'ptrCbMainWindow','trnLoad'});
    menu.trn.item(3) = uimenu(menu.trn.menu, ...
            'Label', ptrLgGetString('menu_TrnDetails'), ...
            'Enable','off', ...
            'Callback', {'ptrCbMainWindow','trnDetails'});

    % View menu
    menu.view.menu = uimenu(ptrData.handles.win,'Label', ...
            ptrLgGetString('menu_View')); 
    menu.view.item(1) = uimenu(menu.view.menu, ...
            'Label', ptrLgGetString('menu_ViewList'), ...
            'Callback', {'ptrCbMainWindow','changeView'});
    menu.view.item(2) = uimenu(menu.view.menu, ...
            'Label', ptrLgGetString('menu_ViewGrid'), ...
            'Callback', {'ptrCbMainWindow','changeView'});
    menu.view.item(3) = uimenu(menu.view.menu, ...
            'Label', ptrLgGetString('menu_ViewSec'), ...
            'Callback', {'ptrCbMainWindow','changeView'});
    set (menu.view.item(ptrData.params.displayMode), ...
         'Checked', 'on');
    
    % Languages menu
    menu.lang.menu = uimenu(ptrData.handles.win,'Label', ...
        ptrLgGetString('menu_Lang'));
    for i=1:numel(ptrData.params.langData)
        if strcmp (ptrData.params.langData(i).code, ptrData.params.langSelected), 
            ck = 'on'; 
        else
            ck = 'off';
        end
        
        menu.lang.item(i) = uimenu(menu.lang.menu, ...
                'Label', ptrData.params.langData(i).name, ...
                'Checked', ck, ...
                'Callback', {'ptrCbMainWindow','changeLang'});
    end

    % Colormaps menu
    menu.colormaps.menu = uimenu(ptrData.handles.win,'Label', ...
        ptrLgGetString('menu_Colormaps'));
    names = fieldnames(ptrData.params.colormaps);
    for i=1:numel(names)
        if strcmp(names{i}, ptrData.params.colormapName), 
            ck = 'on'; 
        else
            ck = 'off';
        end
        
        menu.colormaps.item(i) = uimenu( ...
                menu.colormaps.menu, ...
                'Label', names{i}, ...
                'Checked', ck, ...
                'Callback', {'ptrCbMainWindow','changeColormap'});
    end

    ptrData.handles.menu = menu;

    
    % Toolbar
    %bgColor = get(0, 'factoryUicontainerBackgroundColor');
    toolbar.toolbar = uitoolbar('Parent', ptrData.handles.win);
    drawnow;
    jToolbar = get(get(toolbar.toolbar,'JavaContainer'),'ComponentPeer');    
    bgColor = get (jToolbar,'Background');
    
    % Toolbar buttons
    toolbar.button(1) = uipushtool('Parent', toolbar.toolbar, ...
            'CData', ptrLoadIcon(ptrData.params,'open',bgColor), ...
            'ClickedCallback', {'ptrCbMainWindow','imgOpen'});
    toolbar.button(2) = uipushtool('Parent', toolbar.toolbar, ...
            'CData', ptrLoadIcon(ptrData.params,'save',bgColor), ...
            'ClickedCallback', {'ptrCbMainWindow','imgSave'});
    toolbar.button(3) = uipushtool('Parent', toolbar.toolbar, ...
            'CData', ptrLoadIcon(ptrData.params,'close',bgColor), ...
            'ClickedCallback', {'ptrCbMainWindow','imgClose'});


    % Image tools
    toolbar.imgTools.button(1) = uitoggletool('Parent', toolbar.toolbar, ...
            'Separator', 'on', ...
            'CData', ptrLoadIcon(ptrData.params,'zoom_in',bgColor), ...
            'Visible', 'off', ...
            'Tag','Toolbar.ImageTool', ...
            'ClickedCallback', {'ptrPlotTools','zoomIn'});

    toolbar.imgTools.button(2) = uipushtool('Parent', toolbar.toolbar, ...
            'CData', ptrLoadIcon(ptrData.params,'zoom_reset',bgColor), ...
            'Visible', 'off', ...
            'Tag','Toolbar.ImageTool', ...
            'ClickedCallback', {'ptrPlotTools','zoomReset'});
        
    toolbar.imgTools.button(3) = uitoggletool('Parent', toolbar.toolbar, ...
            'CData', ptrLoadIcon(ptrData.params,'zoom_out',bgColor), ...
            'Visible', 'off', ...
            'Tag','Toolbar.ImageTool', ...
            'ClickedCallback', {'ptrPlotTools','zoomOut'});

    toolbar.imgTools.button(4) = uitoggletool('Parent', toolbar.toolbar, ...
            'CData', ptrLoadIcon(ptrData.params,'hand',bgColor), ...
            'Visible', 'off', ...
            'Tag','Toolbar.ImageTool', ...
            'ClickedCallback', {'ptrPlotTools','hand'});




    ptrData.handles.toolbar = toolbar;
    
    guidata(hMainWin, ptrData);
    
    ptrStatusBar(hMainWin, 'create')
end




