%
% Ask for a name and method to create a new training
%
function [name, methodName, methodPath] = ptrDlgCreateTraining(pathMethods)
    name = -1;
    methodName = '';
    methodPath = '';
    winWidth = 370;      % Window width
    winHeight = 140;     % Window height

    % List of available methods
    mNames = [];
    mPaths = [];
    lis = dir(pathMethods);
    for i=1:numel(lis)
        if lis(i).name(1) ~= '.' && lis(i).isdir
            nameFile = [pathMethods filesep lis(i).name ...
                        filesep 'nfo_name.txt'];
            if exist(nameFile,'file')
                mName = textread(nameFile,'%s');
                mNames{numel(mNames)+1} = ptrStrJoin({mName{:}},' ');
                mPaths{numel(mNames)} = lis(i).name;
            end
        end
    end
    if isempty (mNames), mNames = ' '; end
    
    f = figure('Name', ptrLgGetString('dlgEntrenar_Title'), ...
        'NumberTitle', 'off', ...
        'visible','off',...
        'WindowStyle','modal', ...
        'Position', [1 1 winWidth winHeight], ...
        'MenuBar', 'none', ...
        'Resize', 'off', ...
        'UserData', 0);
    ptrCenterWindow(f);

    pan = uipanel('Parent',f, 'BorderType', 'none',...
                  'Units','pixels','Position',[1 1 winWidth winHeight]);
              
    textName = uicontrol('Parent', pan, ...
                  'String', ptrLgGetString('dlgEntrenar_NameLab'), ...
                  'Style', 'text', ...
                  'Units', 'pixels', ...
                  'Position', [20 105 90 15], ...
                  'FontUnits','pixels', ...
                  'FontName', 'Helvetica', ...
                  'FontSize',12, ...
                  'HorizontalAlignment','right');

    editName = uicontrol('Parent', pan, ...
                  'String', '', ...
                  'Style', 'edit', ...
                  'Units', 'pixels', ...
                  'Position', [115 100 225 25], ...
                  'FontUnits','pixels', ...
                  'FontName', 'Helvetica', ...
                  'FontSize',12, ...
                  'HorizontalAlignment','left'); 

    textMethod = uicontrol('Parent', pan, ...
                  'String', ptrLgGetString('dlgEntrenar_MetLab'), ...
                  'Style', 'text', ...
                  'Units', 'pixels', ...
                  'Position', [20 70 90 15], ...
                  'FontUnits','pixels', ...
                  'FontName', 'Helvetica', ...
                  'FontSize',12, ...
                  'HorizontalAlignment','right');

    comboMethod = uicontrol('Parent', pan, ...
                  'String', mNames, ...
                  'Style', 'popupmenu', ...
                  'Units', 'pixels', ...
                  'Position', [115 65 225 25], ...
                  'FontUnits','pixels', ...
                  'FontName', 'Helvetica', ...
                  'FontSize',12, ...
                  'HorizontalAlignment','left'); 
    
    btnOk = uicontrol('Parent',pan, ...
                  'String', ptrLgGetString('all_OkBtn'),...
                  'Units','pixels', ...
                  'Position', [winWidth/2-100 10 90 30], ...
                  'FontUnits', 'pixels', ...
                  'FontName', 'Helvetica', ...
                  'FontSize', 11, ...
                  'FontWeight', 'bold',...
                  'Callback', 'set(gcbf,''UserData'',1); uiresume(gcbf)');
              
    btnCancel = uicontrol('Parent',pan, ...
                  'String', ptrLgGetString('all_CancelBtn'),...
                  'Units','pixels', ...
                  'Position', [winWidth/2+10 10 90 30], ...
                  'FontUnits', 'pixels', ...
                  'FontName', 'Helvetica', ...
                  'FontSize', 11, ...
                  'FontWeight', 'bold',...
                  'Callback', 'uiresume(gcbf)');
              
              
    set(f,'Visible','on');
    drawnow;
    uicontrol(editName);
    uiwait(f);
    if ~ishandle(f), return; end
    if get(f,'UserData') == 1
        name = strtrim(get(editName,'String'));
        methodName = mNames{get(comboMethod,'Value')};
        methodPath = mPaths{get(comboMethod,'Value')};
    end
    close(f); 
end

